
spring.application.name=jdbc-demo
server.port=8080

# ===============================
# DATASOURCE (JDBC)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/users_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA (only if you use @Entity)
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# (or remove this line completely)

# ===============================
# ERROR DETAILS
# ===============================
server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-binding-errors=always
spring.security.user.password=abc@123








#spring.application.name=jdbc-demo
#server.port=8080
#spring.datasource.driver-class-name= com.mysql.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/users_db
#spring.datasource.username=root
#spring.datasource.password=Root@123
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.properties.hibernate.format_sql=true
#
## Always include the error message and the exception stack trace
#server.error.include-message=always
#server.error.include-stacktrace=always
#server.error.include-binding-errors=always
